### ISSUE TITLE
and instead of or

### ISSUE THREAD

**Issue by KipCrossing** [shariltumin/esp32-cam-micropython#1]
In your port3() function, I noticed that you use **or** to (i assume) check if w within the accepted range of integers. This check basically does nothing as it would be true for all integers. I suggest using **and**.

```python
      elif rqp[2] == 'pix':
         w = int(rqp[3])
         if w>0 or w<13: # use and here
            camera.framesize(w)
```

**Comment by shariltumin** [comment]
Hi Kip,
Thanks for pointing out these stupid mistakes. I've done the necessary changes in webcam.py and mth_webcam.py. Thanks again man.

**Comment by KipCrossing** [comment]
No problem!
