### ISSUE TITLE
[Errno 110] ETIMEDOUT

### ISSUE THREAD

**Issue by e135193** [shariltumin/esp32-cam-micropython#16]
I get "[Errno 110] ETIMEDOUT" when I try to connect to the module

```
>>> %Run -c $EDITOR_CONTENT
Camera ready?:  True
I (434783) phy: phy_version: 4102, 2fa7a43, Jul 15 2019, 13:06:06, 0, 0
Waiting ...
Waiting ...
Connected to Noname Wifi
network config: ('192.168.0.26', '255.255.255.0', '192.168.0.1', 'X.X.X.X')
Up Up and Away!
GET / ('192.168.0.11', 54870)
[Errno 110] ETIMEDOUT
```

**Comment by shariltumin** [comment]
In your case please try
http://192.168.0.26/apikey/webcam
this will give you live-stream from the camera

If you want a still photo
http://192.168.0.26:81/apikey/snap

You can change some of camera setting, for example set picture to black and white
http://192.168.0.26:82/apikey/spe/2

**Comment by e135193** [comment]
@shariltumin Thanks for the clarification. It would be nice if you put this on README section of the github, so people can make use of it. 

Best Regards
