### ISSUE TITLE
ov2640 ROI/zoom-pan-tilt

### ISSUE THREAD

**Issue by jacceko** [shariltumin/esp32-cam-micropython#3]
In some implementations of ov2640 in c already on internet are include tilt, pan, zoom (ROI) option which is supported by ov2640 hardware  (for ex: this feature already exists in OpenMV as ROI -> set_windowing: [https://docs.openmv.io/library/omv.sensor.html#sensor.sensor.set_windowing](https://docs.openmv.io/library/omv.sensor.html#sensor.sensor.set_windowing) ,  [https://github.com/openmv/openmv/blob/master/src/omv/sensor.c#L551](https://github.com/openmv/openmv/blob/master/src/omv/sensor.c#L551)
It will be very good add this feature to esp32-cam-micropython. It can be as zoom, pan, tilf or as ROI square, but it will be very helpful if someone need details on image, but don't want to always process big (slow) image.

**Comment by shariltumin** [comment]
espressif esp32-camera implement the ov2640 from OpenMV project. They somewhat disable the windowing capability. Yes it would be nice to have these features included in https://github.com/espressif/esp32-camera.git specifically in sensors/ov2640.c

**Comment by jacceko** [comment]
Thank for answer - I put an issue on esp32-camera on github.
[https://github.com/espressif/esp32-camera/issues/104](https://github.com/espressif/esp32-camera/issues/104)
